#!/usr/bin/env node
/**
 * Seed script: populate marketplace_agents with curated agents based on AutoGPT platform blocks.
 *
 * Usage: node scripts/seed-agents.mjs
 * Prereqs: npm install pg (already available)
 *
 * Automatically loads DATABASE_URL from .env.local if present (same DB as the Next.js frontend).
 */

import pg from 'pg';
import { readFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load .env.local so the seed uses the same DATABASE_URL as the Next.js dev server.
try {
  const envContent = readFileSync(path.join(__dirname, '..', '.env.local'), 'utf-8');
  for (const line of envContent.split('\n')) {
    const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (match) {
      const key = match[1];
      const val = match[2].trim().replace(/^["']|["']$/g, '');
      if (!process.env[key]) process.env[key] = val;
    }
  }
  console.log('Loaded .env.local');
} catch {
  console.log('.env.local not found, using fallback DATABASE_URL');
}

const DATABASE_URL = process.env.DATABASE_URL;

const AGENTS = [
  // ── Customer Support ────────────────────────────────────────────
  {
    slug: 'customer-support-chatbot',
    name: 'Customer Support Chatbot',
    short_description: 'AI-powered customer support agent that handles inquiries, FAQs, and ticket routing.',
    description: 'Automate your customer support with an intelligent AI chatbot. Handles common inquiries, routes complex tickets to human agents, and learns from past interactions to improve over time. Supports multi-channel communication including email, chat, and social media.',
    category: 'customer-support',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.8,
    review_count: 1240,
    total_installs: 15600,
    version: '2.1.0',
    verified: true,
    tags: ['support', 'chatbot', 'faq', 'tickets', 'multi-channel'],
    integrations: ['Discord', 'Slack', 'Email'],
    capabilities: ['Natural language understanding', 'Ticket routing', 'FAQ automation', 'Sentiment analysis'],
    key_benefits: [
      { title: '24/7 Availability', description: 'Never miss a customer inquiry' },
      { title: 'Smart Routing', description: 'Automatically escalates complex issues' },
      { title: 'Multi-Language', description: 'Supports 50+ languages' },
    ],
    about: 'Built on AutoGPT\'s advanced LLM blocks, this agent combines natural language understanding with intelligent routing to deliver exceptional customer support experiences.',
  },
  {
    slug: 'email-responder-agent',
    name: 'Email Responder Agent',
    short_description: 'Automatically drafts and sends email responses based on incoming customer emails.',
    description: 'This agent monitors your inbox, understands customer emails, and drafts professional responses. It learns your tone and style over time, ensuring consistent communication. Integrates with Gmail, Outlook, and custom SMTP servers.',
    category: 'customer-support',
    developer: 'AutoGPT',
    price: 9.99,
    price_label: '$9.99/mo',
    rating: 4.6,
    review_count: 890,
    total_installs: 8200,
    version: '1.5.0',
    verified: true,
    tags: ['email', 'auto-reply', 'customer-service', 'gmail', 'outlook'],
    integrations: ['Gmail', 'Outlook', 'SMTP'],
    capabilities: ['Email parsing', 'Tone matching', 'Auto-drafting', 'Follow-up scheduling'],
    key_benefits: [
      { title: 'Time Saver', description: 'Draft responses in seconds' },
      { title: 'Consistent Tone', description: 'Maintains your brand voice' },
    ],
    about: 'Powered by AutoGPT\'s email integration blocks and LLM text generation.',
  },

  // ── Sales & Marketing ───────────────────────────────────────────
  {
    slug: 'lead-generation-agent',
    name: 'Lead Generation Agent',
    short_description: 'Discovers and qualifies leads using web scraping and AI-powered analysis.',
    description: 'Automatically discover potential leads by scraping websites, social media, and business directories. The agent qualifies leads based on your ideal customer profile and enriches contact data using multiple data sources. Integrates with CRM systems like HubSpot and Salesforce.',
    category: 'sales',
    developer: 'AutoGPT',
    price: 19.99,
    price_label: '$19.99/mo',
    rating: 4.7,
    review_count: 670,
    total_installs: 5400,
    version: '1.8.0',
    verified: true,
    tags: ['leads', 'scraping', 'crm', 'prospecting', 'sales'],
    integrations: ['HubSpot', 'Salesforce', 'Apollo', 'LinkedIn'],
    capabilities: ['Web scraping', 'Lead scoring', 'Data enrichment', 'CRM sync'],
    key_benefits: [
      { title: 'Automated Prospecting', description: 'Find leads while you sleep' },
      { title: 'AI Scoring', description: 'Focus on high-value prospects' },
    ],
    about: 'Combines AutoGPT\'s web scraping blocks (Firecrawl, Exa) with Apollo data enrichment and CRM integrations.',
  },
  {
    slug: 'social-media-manager',
    name: 'Social Media Manager',
    short_description: 'Creates, schedules, and publishes social media content across platforms.',
    description: 'Manage your entire social media presence with AI. This agent creates engaging posts, schedules them for optimal times, and analyzes engagement metrics. Supports Twitter/X, LinkedIn, Instagram, Facebook, and more through Ayrshare integration.',
    category: 'sales',
    developer: 'AutoGPT',
    price: 14.99,
    price_label: '$14.99/mo',
    rating: 4.5,
    review_count: 1100,
    total_installs: 12300,
    version: '2.0.0',
    verified: true,
    tags: ['social-media', 'content', 'scheduling', 'analytics', 'marketing'],
    integrations: ['Twitter', 'LinkedIn', 'Instagram', 'Ayrshare'],
    capabilities: ['Content generation', 'Post scheduling', 'Analytics tracking', 'Hashtag optimization'],
    key_benefits: [
      { title: 'Multi-Platform', description: 'Post everywhere at once' },
      { title: 'AI Content', description: 'Generate engaging posts automatically' },
    ],
    about: 'Uses AutoGPT\'s Ayrshare social media blocks for publishing and LLM blocks for content creation.',
  },
  {
    slug: 'seo-optimizer-agent',
    name: 'SEO Optimizer Agent',
    short_description: 'Analyzes and optimizes your website content for search engine rankings.',
    description: 'Improve your search rankings with AI-powered SEO analysis. This agent crawls your website, identifies optimization opportunities, generates keyword suggestions, and creates SEO-optimized content. Uses DataForSEO for competitive analysis.',
    category: 'sales',
    developer: 'AutoGPT',
    price: 24.99,
    price_label: '$24.99/mo',
    rating: 4.4,
    review_count: 430,
    total_installs: 3800,
    version: '1.3.0',
    verified: true,
    tags: ['seo', 'keywords', 'ranking', 'optimization', 'content'],
    integrations: ['DataForSEO', 'Google Search Console', 'Firecrawl'],
    capabilities: ['Site auditing', 'Keyword research', 'Content optimization', 'Competitor analysis'],
    key_benefits: [
      { title: 'Higher Rankings', description: 'Data-driven SEO improvements' },
      { title: 'Content Ideas', description: 'AI-generated content briefs' },
    ],
    about: 'Built with AutoGPT\'s DataForSEO and Firecrawl blocks for comprehensive search optimization.',
  },

  // ── Content & Writing ────────────────────────────────────────────
  {
    slug: 'blog-writer-agent',
    name: 'Blog Writer Agent',
    short_description: 'Researches topics and writes high-quality blog posts with SEO optimization.',
    description: 'Generate publish-ready blog posts automatically. This agent researches your topic using web search, creates detailed outlines, writes engaging content, and optimizes for SEO. Supports multiple writing styles and tones. Outputs in Markdown or HTML.',
    category: 'writing',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.9,
    review_count: 2100,
    total_installs: 28500,
    version: '3.0.0',
    verified: true,
    tags: ['blog', 'writing', 'seo', 'content-creation', 'articles'],
    integrations: ['WordPress', 'Medium', 'Ghost', 'Exa Search'],
    capabilities: ['Topic research', 'Content writing', 'SEO optimization', 'Image suggestions'],
    key_benefits: [
      { title: 'Research-Backed', description: 'Content grounded in real data' },
      { title: 'SEO-Ready', description: 'Optimized for search from the start' },
      { title: 'Your Voice', description: 'Adapts to your brand tone' },
    ],
    about: 'AutoGPT\'s most popular content agent, combining web research (Exa), LLM writing, and SEO analysis blocks.',
  },
  {
    slug: 'copywriting-assistant',
    name: 'Copywriting Assistant',
    short_description: 'Creates compelling ad copy, taglines, and marketing materials.',
    description: 'Craft persuasive marketing copy in seconds. From ad headlines to product descriptions, email campaigns to landing pages — this agent generates conversion-focused copy that resonates with your target audience.',
    category: 'writing',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.7,
    review_count: 950,
    total_installs: 11200,
    version: '1.6.0',
    verified: true,
    tags: ['copywriting', 'ads', 'headlines', 'conversion', 'marketing'],
    integrations: ['Google Ads', 'Facebook Ads'],
    capabilities: ['Ad copy generation', 'A/B testing variations', 'Tone adjustment', 'Headline optimization'],
    key_benefits: [
      { title: 'High Converting', description: 'Proven copywriting frameworks' },
      { title: 'Multiple Variants', description: 'Generate A/B test options' },
    ],
    about: 'Leverages AutoGPT\'s LLM blocks with copywriting-specific prompts and frameworks.',
  },
  {
    slug: 'document-summarizer',
    name: 'Document Summarizer',
    short_description: 'Summarizes long documents, PDFs, and articles into concise key points.',
    description: 'Extract key insights from lengthy documents instantly. Upload PDFs, paste URLs, or input text — the agent produces executive summaries, bullet-point takeaways, and action items. Perfect for research papers, reports, and meeting notes.',
    category: 'writing',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.6,
    review_count: 780,
    total_installs: 9800,
    version: '1.4.0',
    verified: true,
    tags: ['summarize', 'documents', 'pdf', 'research', 'notes'],
    integrations: ['Google Drive', 'Notion', 'PDF'],
    capabilities: ['PDF parsing', 'Text summarization', 'Key point extraction', 'Action item detection'],
    key_benefits: [
      { title: 'Save Hours', description: 'Summarize in seconds, not hours' },
      { title: 'Actionable', description: 'Extract action items automatically' },
    ],
    about: 'Uses AutoGPT\'s text processing and LLM summarization blocks.',
  },

  // ── Code & Development ──────────────────────────────────────────
  {
    slug: 'code-reviewer-agent',
    name: 'Code Reviewer Agent',
    short_description: 'Reviews code for bugs, security issues, and best practice violations.',
    description: 'Get instant AI-powered code reviews. This agent analyzes pull requests and code changes for bugs, security vulnerabilities, performance issues, and coding standard violations. Supports Python, JavaScript, TypeScript, Go, and more.',
    category: 'coding',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.8,
    review_count: 1560,
    total_installs: 18900,
    version: '2.2.0',
    verified: true,
    tags: ['code-review', 'security', 'bugs', 'github', 'pull-request'],
    integrations: ['GitHub', 'GitLab', 'Bitbucket'],
    capabilities: ['Bug detection', 'Security scanning', 'Style checking', 'Performance analysis'],
    key_benefits: [
      { title: 'Catch Bugs Early', description: 'AI finds issues humans miss' },
      { title: 'Security First', description: 'OWASP-aware scanning' },
      { title: 'Instant Feedback', description: 'Reviews in seconds' },
    ],
    about: 'Built with AutoGPT\'s GitHub integration blocks and LLM code analysis capabilities.',
  },
  {
    slug: 'github-pr-agent',
    name: 'GitHub PR Agent',
    short_description: 'Automates GitHub PR management — labels, reviews, and merges.',
    description: 'Streamline your GitHub workflow. This agent monitors repositories, auto-labels PRs, requests reviewers, runs checks, and can auto-merge when criteria are met. Includes issue triage and project board management.',
    category: 'coding',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.5,
    review_count: 890,
    total_installs: 7600,
    version: '1.7.0',
    verified: true,
    tags: ['github', 'pull-request', 'automation', 'devops', 'ci-cd'],
    integrations: ['GitHub', 'Slack', 'Discord'],
    capabilities: ['PR labeling', 'Auto-review', 'Issue triage', 'Merge automation'],
    key_benefits: [
      { title: 'Faster Shipping', description: 'Automate PR workflow' },
      { title: 'Smart Labeling', description: 'AI-powered categorization' },
    ],
    about: 'Powered by AutoGPT\'s comprehensive GitHub blocks: issues, PRs, comments, labels, and more.',
  },
  {
    slug: 'api-testing-agent',
    name: 'API Testing Agent',
    short_description: 'Generates and runs API tests automatically from OpenAPI specs.',
    description: 'Automatically generate comprehensive API test suites from your OpenAPI/Swagger specs. The agent creates test cases, runs them, and reports results. Catches breaking changes before they reach production.',
    category: 'coding',
    developer: 'AutoGPT',
    price: 9.99,
    price_label: '$9.99/mo',
    rating: 4.3,
    review_count: 340,
    total_installs: 2900,
    version: '1.2.0',
    verified: true,
    tags: ['api', 'testing', 'openapi', 'swagger', 'automation'],
    integrations: ['Postman', 'GitHub Actions'],
    capabilities: ['Test generation', 'API monitoring', 'Breaking change detection', 'Report generation'],
    key_benefits: [
      { title: 'Auto-Generated Tests', description: 'From spec to tests instantly' },
      { title: 'CI Integration', description: 'Run in your pipeline' },
    ],
    about: 'Combines AutoGPT\'s HTTP request blocks with LLM-powered test case generation.',
  },

  // ── Data & Analytics ────────────────────────────────────────────
  {
    slug: 'data-analyst-agent',
    name: 'Data Analyst Agent',
    short_description: 'Analyzes datasets, generates insights, and creates visualizations.',
    description: 'Turn raw data into actionable insights. Upload CSV files, connect databases, or paste data — the agent performs statistical analysis, identifies trends, detects anomalies, and generates clear visualizations and reports.',
    category: 'data',
    developer: 'AutoGPT',
    price: 14.99,
    price_label: '$14.99/mo',
    rating: 4.7,
    review_count: 560,
    total_installs: 6100,
    version: '1.9.0',
    verified: true,
    tags: ['analytics', 'data', 'visualization', 'statistics', 'reports'],
    integrations: ['Google Sheets', 'Airtable', 'PostgreSQL'],
    capabilities: ['Statistical analysis', 'Trend detection', 'Anomaly detection', 'Chart generation'],
    key_benefits: [
      { title: 'Instant Insights', description: 'From data to decisions fast' },
      { title: 'Visual Reports', description: 'Auto-generated charts' },
    ],
    about: 'Uses AutoGPT\'s Airtable and data processing blocks with LLM-driven analysis.',
  },
  {
    slug: 'web-scraper-agent',
    name: 'Web Scraper Agent',
    short_description: 'Scrapes websites and extracts structured data automatically.',
    description: 'Extract data from any website with AI-powered scraping. Point the agent at a URL, describe what data you need, and it handles the rest — pagination, JavaScript rendering, and data structuring included. Uses Firecrawl for reliable extraction.',
    category: 'data',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.6,
    review_count: 1300,
    total_installs: 16800,
    version: '2.3.0',
    verified: true,
    tags: ['scraping', 'extraction', 'web', 'data-collection', 'automation'],
    integrations: ['Firecrawl', 'Google Sheets', 'Airtable'],
    capabilities: ['AI scraping', 'Pagination handling', 'JS rendering', 'Data structuring'],
    key_benefits: [
      { title: 'No-Code Scraping', description: 'Just describe what you need' },
      { title: 'Reliable', description: 'Handles dynamic websites' },
    ],
    about: 'Built on AutoGPT\'s Firecrawl integration blocks for enterprise-grade web scraping.',
  },
  {
    slug: 'spreadsheet-automator',
    name: 'Spreadsheet Automator',
    short_description: 'Automates Google Sheets and Airtable operations with AI intelligence.',
    description: 'Automate repetitive spreadsheet tasks. This agent can clean data, apply formulas, merge sheets, generate pivot tables, and create reports — all through natural language commands. Works with Google Sheets and Airtable.',
    category: 'data',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.4,
    review_count: 620,
    total_installs: 5500,
    version: '1.5.0',
    verified: false,
    tags: ['spreadsheet', 'google-sheets', 'airtable', 'automation', 'data'],
    integrations: ['Google Sheets', 'Airtable', 'CSV'],
    capabilities: ['Data cleaning', 'Formula generation', 'Report creation', 'Data merging'],
    key_benefits: [
      { title: 'Natural Language', description: 'Tell it what you need in plain English' },
      { title: 'Multi-Source', description: 'Works with Sheets and Airtable' },
    ],
    about: 'Powered by AutoGPT\'s Google Sheets and Airtable integration blocks.',
  },

  // ── HR & Recruiting ─────────────────────────────────────────────
  {
    slug: 'resume-screener-agent',
    name: 'Resume Screener Agent',
    short_description: 'Screens resumes and ranks candidates based on job requirements.',
    description: 'Automate your hiring pipeline. Upload job descriptions and resumes — the agent analyzes each candidate, scores them against requirements, identifies top matches, and generates shortlists with detailed reasoning.',
    category: 'hr',
    developer: 'AutoGPT',
    price: 19.99,
    price_label: '$19.99/mo',
    rating: 4.5,
    review_count: 380,
    total_installs: 3200,
    version: '1.4.0',
    verified: true,
    tags: ['resume', 'hiring', 'recruiting', 'screening', 'hr'],
    integrations: ['Google Drive', 'Dropbox'],
    capabilities: ['Resume parsing', 'Candidate scoring', 'Skill matching', 'Shortlist generation'],
    key_benefits: [
      { title: 'Unbiased Screening', description: 'Consistent evaluation criteria' },
      { title: 'Fast Turnaround', description: 'Screen hundreds in minutes' },
    ],
    about: 'Uses AutoGPT\'s document processing and LLM analysis blocks for intelligent resume screening.',
  },
  {
    slug: 'interview-prep-agent',
    name: 'Interview Prep Agent',
    short_description: 'Generates interview questions and evaluates candidate responses.',
    description: 'Prepare better interviews with AI. This agent generates role-specific questions, creates scoring rubrics, and can even evaluate recorded responses. Supports technical, behavioral, and situational interview formats.',
    category: 'hr',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.3,
    review_count: 290,
    total_installs: 2800,
    version: '1.1.0',
    verified: false,
    tags: ['interview', 'questions', 'hiring', 'evaluation', 'hr'],
    integrations: ['Google Calendar', 'Zoom'],
    capabilities: ['Question generation', 'Rubric creation', 'Response evaluation', 'Report generation'],
    key_benefits: [
      { title: 'Structured Interviews', description: 'Consistent evaluation criteria' },
      { title: 'Role-Specific', description: 'Tailored to each position' },
    ],
    about: 'Leverages AutoGPT\'s LLM blocks for intelligent interview preparation and evaluation.',
  },

  // ── Finance & Accounting ────────────────────────────────────────
  {
    slug: 'invoice-processor-agent',
    name: 'Invoice Processor Agent',
    short_description: 'Extracts data from invoices and automates bookkeeping entries.',
    description: 'Streamline your accounts payable. This agent reads invoices (PDF, images, email), extracts key data (amounts, dates, vendors), categorizes expenses, and creates bookkeeping entries. Integrates with QuickBooks and Xero.',
    category: 'finance',
    developer: 'AutoGPT',
    price: 14.99,
    price_label: '$14.99/mo',
    rating: 4.6,
    review_count: 410,
    total_installs: 4200,
    version: '1.6.0',
    verified: true,
    tags: ['invoice', 'accounting', 'bookkeeping', 'finance', 'automation'],
    integrations: ['QuickBooks', 'Xero', 'Gmail'],
    capabilities: ['Invoice parsing', 'Data extraction', 'Expense categorization', 'Bookkeeping automation'],
    key_benefits: [
      { title: 'Eliminate Manual Entry', description: 'Auto-extract invoice data' },
      { title: 'Accurate', description: '99%+ extraction accuracy' },
    ],
    about: 'Combines AutoGPT\'s document processing blocks with accounting system integrations.',
  },
  {
    slug: 'financial-report-agent',
    name: 'Financial Report Agent',
    short_description: 'Generates financial reports, forecasts, and budget analyses.',
    description: 'Create comprehensive financial reports automatically. The agent pulls data from your accounting system, generates P&L statements, cash flow analysis, budget variance reports, and financial forecasts with trend analysis.',
    category: 'finance',
    developer: 'AutoGPT',
    price: 29.99,
    price_label: '$29.99/mo',
    rating: 4.4,
    review_count: 210,
    total_installs: 1800,
    version: '1.2.0',
    verified: true,
    tags: ['finance', 'reports', 'forecasting', 'budgeting', 'analytics'],
    integrations: ['QuickBooks', 'Google Sheets', 'Excel'],
    capabilities: ['Report generation', 'Trend analysis', 'Budget forecasting', 'Variance analysis'],
    key_benefits: [
      { title: 'Auto Reports', description: 'Monthly reports on autopilot' },
      { title: 'AI Forecasting', description: 'Predictive financial analysis' },
    ],
    about: 'Uses AutoGPT\'s data analysis and document generation blocks for financial intelligence.',
  },

  // ── Operations ──────────────────────────────────────────────────
  {
    slug: 'workflow-automator',
    name: 'Workflow Automator',
    short_description: 'Creates multi-step automated workflows connecting your favorite tools.',
    description: 'Build powerful automations without code. Connect apps, trigger actions based on events, and create complex multi-step workflows. The AI understands your intent and builds the workflow for you. Supports webhooks, APIs, and 50+ integrations.',
    category: 'operations',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.8,
    review_count: 1890,
    total_installs: 22000,
    version: '3.1.0',
    verified: true,
    tags: ['automation', 'workflow', 'integration', 'no-code', 'triggers'],
    integrations: ['Webhooks', 'REST API', 'Slack', 'Discord', 'Email'],
    capabilities: ['Event triggers', 'Multi-step flows', 'Conditional logic', 'Error handling'],
    key_benefits: [
      { title: 'No-Code Builder', description: 'Build workflows with AI' },
      { title: '50+ Integrations', description: 'Connect all your tools' },
      { title: 'Reliable', description: 'Built-in error handling and retries' },
    ],
    about: 'The core AutoGPT platform agent — uses the full block ecosystem for unlimited automation possibilities.',
  },
  {
    slug: 'notification-hub-agent',
    name: 'Notification Hub Agent',
    short_description: 'Centralizes and intelligently routes notifications across platforms.',
    description: 'Stop notification overload. This agent aggregates alerts from all your tools, filters noise, prioritizes critical notifications, and delivers summaries. Supports Slack, Discord, Email, SMS, and push notifications.',
    category: 'operations',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.3,
    review_count: 520,
    total_installs: 4800,
    version: '1.3.0',
    verified: false,
    tags: ['notifications', 'alerts', 'slack', 'discord', 'routing'],
    integrations: ['Slack', 'Discord', 'Email', 'SMS'],
    capabilities: ['Alert aggregation', 'Priority filtering', 'Smart routing', 'Summary digests'],
    key_benefits: [
      { title: 'Less Noise', description: 'AI filters unimportant alerts' },
      { title: 'Smart Digests', description: 'Daily/hourly summaries' },
    ],
    about: 'Combines AutoGPT\'s Discord and Slack blocks with intelligent notification routing.',
  },
  {
    slug: 'meeting-assistant-agent',
    name: 'Meeting Assistant Agent',
    short_description: 'Transcribes meetings, generates summaries, and tracks action items.',
    description: 'Never miss a meeting detail again. This agent transcribes your meetings in real-time, generates structured summaries, extracts action items with assignees, and sends follow-up emails. Supports Zoom, Google Meet, and Teams.',
    category: 'operations',
    developer: 'AutoGPT',
    price: 9.99,
    price_label: '$9.99/mo',
    rating: 4.7,
    review_count: 740,
    total_installs: 8900,
    version: '1.8.0',
    verified: true,
    tags: ['meetings', 'transcription', 'summary', 'action-items', 'notes'],
    integrations: ['Zoom', 'Google Meet', 'Slack', 'ElevenLabs'],
    capabilities: ['Transcription', 'Summarization', 'Action item extraction', 'Follow-up automation'],
    key_benefits: [
      { title: 'Auto Notes', description: 'Structured meeting summaries' },
      { title: 'Action Tracking', description: 'Never forget a follow-up' },
    ],
    about: 'Uses AutoGPT\'s ElevenLabs speech blocks and LLM summarization for meeting intelligence.',
  },

  // ── Legal & Compliance ──────────────────────────────────────────
  {
    slug: 'contract-reviewer-agent',
    name: 'Contract Reviewer Agent',
    short_description: 'Reviews contracts and highlights risky clauses and missing terms.',
    description: 'Get AI-powered contract reviews in minutes. Upload contracts and the agent identifies risky clauses, missing standard terms, unusual conditions, and compliance issues. Generates a detailed risk report with recommendations.',
    category: 'legal',
    developer: 'AutoGPT',
    price: 24.99,
    price_label: '$24.99/mo',
    rating: 4.5,
    review_count: 320,
    total_installs: 2600,
    version: '1.3.0',
    verified: true,
    tags: ['contracts', 'legal', 'review', 'risk', 'compliance'],
    integrations: ['Google Drive', 'DocuSign'],
    capabilities: ['Clause analysis', 'Risk identification', 'Missing term detection', 'Report generation'],
    key_benefits: [
      { title: 'Risk Detection', description: 'Spot problematic clauses instantly' },
      { title: 'Fast Reviews', description: 'Minutes instead of hours' },
    ],
    about: 'Leverages AutoGPT\'s document processing and legal-trained LLM analysis blocks.',
  },
  {
    slug: 'compliance-monitor-agent',
    name: 'Compliance Monitor Agent',
    short_description: 'Monitors regulatory changes and checks compliance across documents.',
    description: 'Stay compliant automatically. This agent monitors regulatory updates, scans your policies and procedures for compliance gaps, and alerts you to required changes. Supports GDPR, HIPAA, SOC2, and custom frameworks.',
    category: 'legal',
    developer: 'AutoGPT',
    price: 34.99,
    price_label: '$34.99/mo',
    rating: 4.2,
    review_count: 180,
    total_installs: 1200,
    version: '1.1.0',
    verified: true,
    tags: ['compliance', 'regulatory', 'gdpr', 'hipaa', 'monitoring'],
    integrations: ['Google Drive', 'Notion', 'Slack'],
    capabilities: ['Regulatory monitoring', 'Gap analysis', 'Policy scanning', 'Alert notifications'],
    key_benefits: [
      { title: 'Stay Current', description: 'Auto-track regulatory changes' },
      { title: 'Gap Analysis', description: 'Find compliance gaps proactively' },
    ],
    about: 'Combines AutoGPT\'s web monitoring and document analysis blocks for compliance intelligence.',
  },

  // ── Creative & Design ───────────────────────────────────────────
  {
    slug: 'image-generator-agent',
    name: 'Image Generator Agent',
    short_description: 'Creates custom images, illustrations, and graphics using AI.',
    description: 'Generate stunning visuals with AI. Describe what you need — marketing graphics, product mockups, social media images, or illustrations — and the agent creates them in seconds. Supports multiple styles and aspect ratios through FAL AI and FLUX models.',
    category: 'creative',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.8,
    review_count: 2400,
    total_installs: 31000,
    version: '2.5.0',
    verified: true,
    tags: ['image', 'generation', 'ai-art', 'design', 'graphics'],
    integrations: ['FAL AI', 'FLUX', 'Bannerbear'],
    capabilities: ['Image generation', 'Style transfer', 'Image editing', 'Batch creation'],
    key_benefits: [
      { title: 'Instant Graphics', description: 'Create images in seconds' },
      { title: 'Multiple Styles', description: 'Photo-realistic to illustration' },
      { title: 'Brand Assets', description: 'Consistent visual identity' },
    ],
    about: 'Powered by AutoGPT\'s FAL AI image generation and Bannerbear design automation blocks.',
  },
  {
    slug: 'video-editor-agent',
    name: 'Video Editor Agent',
    short_description: 'Creates and edits videos with AI narration and text overlays.',
    description: 'Automate video production. This agent downloads clips, trims and concatenates footage, adds text overlays, and generates AI narration. Perfect for marketing videos, tutorials, documentaries, and social media content.',
    category: 'creative',
    developer: 'AutoGPT',
    price: 19.99,
    price_label: '$19.99/mo',
    rating: 4.4,
    review_count: 450,
    total_installs: 3600,
    version: '1.0.0',
    verified: true,
    tags: ['video', 'editing', 'narration', 'ai-video', 'content'],
    integrations: ['ElevenLabs', 'YouTube', 'Vimeo'],
    capabilities: ['Video clipping', 'Concatenation', 'Text overlays', 'AI narration'],
    key_benefits: [
      { title: 'AI Narration', description: 'ElevenLabs-powered voiceover' },
      { title: 'No Editor Needed', description: 'Full video pipeline' },
    ],
    about: 'Built with AutoGPT\'s video editing blocks: clip, concat, overlay, and ElevenLabs narration.',
  },
  {
    slug: 'text-to-speech-agent',
    name: 'Text-to-Speech Agent',
    short_description: 'Converts text to natural-sounding speech with multiple voice options.',
    description: 'Generate lifelike speech from text using ElevenLabs\' advanced voice AI. Choose from dozens of voices, adjust speed and tone, and create audio content for podcasts, announcements, accessibility, and more.',
    category: 'creative',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.7,
    review_count: 890,
    total_installs: 10500,
    version: '1.4.0',
    verified: true,
    tags: ['tts', 'speech', 'voice', 'audio', 'elevenlabs'],
    integrations: ['ElevenLabs', 'Google Drive'],
    capabilities: ['Text-to-speech', 'Voice cloning', 'Multi-language', 'Audio export'],
    key_benefits: [
      { title: 'Natural Voices', description: 'Lifelike AI speech' },
      { title: 'Custom Voices', description: 'Clone any voice' },
    ],
    about: 'Powered by AutoGPT\'s ElevenLabs integration blocks for premium text-to-speech.',
  },

  // ── More versatile agents ──────────────────────────────────────
  {
    slug: 'research-assistant-agent',
    name: 'Research Assistant Agent',
    short_description: 'Conducts deep research on any topic using multiple web sources.',
    description: 'Get comprehensive research done in minutes. This agent searches the web, reads articles, cross-references sources, and produces structured research reports with citations. Uses Exa, Firecrawl, and Brave Search for thorough coverage.',
    category: 'data',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.9,
    review_count: 1800,
    total_installs: 25000,
    version: '2.4.0',
    verified: true,
    tags: ['research', 'web-search', 'analysis', 'reports', 'citations'],
    integrations: ['Exa', 'Firecrawl', 'Brave Search', 'Google'],
    capabilities: ['Multi-source search', 'Source verification', 'Report generation', 'Citation management'],
    key_benefits: [
      { title: 'Deep Research', description: 'Multiple sources cross-referenced' },
      { title: 'Cited Reports', description: 'Proper source attribution' },
      { title: 'Fast', description: 'Hours of research in minutes' },
    ],
    about: 'AutoGPT\'s research powerhouse: combines Exa search, Firecrawl scraping, and LLM analysis.',
  },
  {
    slug: 'translation-agent',
    name: 'Translation Agent',
    short_description: 'Translates content between 100+ languages with context-aware accuracy.',
    description: 'Professional-quality translations powered by AI. This agent translates documents, websites, and text while preserving context, tone, and formatting. Supports 100+ languages with specialized terminology handling for legal, medical, and technical content.',
    category: 'writing',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.5,
    review_count: 670,
    total_installs: 7200,
    version: '1.6.0',
    verified: true,
    tags: ['translation', 'languages', 'localization', 'multilingual'],
    integrations: ['Google Translate', 'DeepL'],
    capabilities: ['Document translation', 'Context preservation', 'Terminology handling', 'Batch processing'],
    key_benefits: [
      { title: 'Context-Aware', description: 'Better than word-by-word translation' },
      { title: '100+ Languages', description: 'Comprehensive language support' },
    ],
    about: 'Uses AutoGPT\'s LLM blocks with translation-optimized prompts for natural results.',
  },
  {
    slug: 'discord-community-agent',
    name: 'Discord Community Agent',
    short_description: 'Manages Discord servers with moderation, welcome flows, and engagement.',
    description: 'Automate your Discord community management. This agent handles moderation, welcomes new members, answers FAQ questions, runs engagement activities, and generates community analytics reports.',
    category: 'operations',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.6,
    review_count: 1100,
    total_installs: 13500,
    version: '2.0.0',
    verified: true,
    tags: ['discord', 'community', 'moderation', 'engagement', 'bot'],
    integrations: ['Discord', 'Notion'],
    capabilities: ['Auto-moderation', 'Welcome flows', 'FAQ bot', 'Analytics'],
    key_benefits: [
      { title: '24/7 Moderation', description: 'Always-on community safety' },
      { title: 'Engagement', description: 'Automated community activities' },
    ],
    about: 'Built with AutoGPT\'s Discord integration blocks for comprehensive community management.',
  },
  {
    slug: 'google-workspace-agent',
    name: 'Google Workspace Agent',
    short_description: 'Automates Google Workspace tasks — Docs, Sheets, Drive, and Calendar.',
    description: 'Supercharge your Google Workspace productivity. This agent creates documents, manages spreadsheets, organizes Drive files, schedules calendar events, and automates cross-app workflows. Works with Docs, Sheets, Slides, Drive, and Calendar.',
    category: 'operations',
    developer: 'AutoGPT',
    price: 0,
    price_label: 'Free',
    rating: 4.5,
    review_count: 780,
    total_installs: 9200,
    version: '1.7.0',
    verified: true,
    tags: ['google', 'workspace', 'docs', 'sheets', 'drive', 'calendar'],
    integrations: ['Google Docs', 'Google Sheets', 'Google Drive', 'Google Calendar'],
    capabilities: ['Document creation', 'Spreadsheet automation', 'File management', 'Calendar scheduling'],
    key_benefits: [
      { title: 'All-in-One', description: 'Covers all Google Workspace apps' },
      { title: 'Cross-App', description: 'Workflows across Google apps' },
    ],
    about: 'Powered by AutoGPT\'s comprehensive Google integration blocks.',
  },
  {
    slug: 'competitor-analysis-agent',
    name: 'Competitor Analysis Agent',
    short_description: 'Monitors competitors and provides market intelligence reports.',
    description: 'Stay ahead of the competition. This agent monitors competitor websites, tracks pricing changes, analyzes their content strategy, and compiles weekly intelligence reports. Uses web scraping and AI analysis for comprehensive insights.',
    category: 'sales',
    developer: 'AutoGPT',
    price: 19.99,
    price_label: '$19.99/mo',
    rating: 4.3,
    review_count: 290,
    total_installs: 2400,
    version: '1.2.0',
    verified: true,
    tags: ['competitor', 'analysis', 'market-intelligence', 'monitoring', 'strategy'],
    integrations: ['Firecrawl', 'Exa', 'Google Sheets'],
    capabilities: ['Website monitoring', 'Price tracking', 'Content analysis', 'Report generation'],
    key_benefits: [
      { title: 'Stay Informed', description: 'Automatic competitor tracking' },
      { title: 'Weekly Reports', description: 'Structured intelligence briefs' },
    ],
    about: 'Combines AutoGPT\'s Firecrawl web scraping with LLM analysis for competitive intelligence.',
  },
];

async function main() {
  console.log('Connecting to database...');
  // Use explicit params to avoid URL encoding issues with special chars in password
  const client = DATABASE_URL
    ? new pg.Client({ connectionString: DATABASE_URL, ssl: { rejectUnauthorized: false } })
    : new pg.Client({ host: 'mawadao.db', port: 5432, database: 'mawadao', user: 'postgres', password: 'Zh%F+obR$dp-6\\A-', ssl: { rejectUnauthorized: false } });
  await client.connect();
  console.log('Connected.');

  // Build batch insert
  const values = [];
  const params = [];
  let paramIdx = 1;

  for (const agent of AGENTS) {
    values.push(
      `($${paramIdx}, $${paramIdx+1}, $${paramIdx+2}, $${paramIdx+3}, $${paramIdx+4}, $${paramIdx+5}, $${paramIdx+6}, $${paramIdx+7}, $${paramIdx+8}, $${paramIdx+9}, $${paramIdx+10}, $${paramIdx+11}, $${paramIdx+12}, $${paramIdx+13}, $${paramIdx+14}, $${paramIdx+15}, $${paramIdx+16}, $${paramIdx+17}, $${paramIdx+18})`
    );
    params.push(
      agent.slug,
      agent.name,
      agent.description,
      agent.short_description,
      agent.category,
      agent.developer,
      agent.price,
      agent.price_label,
      agent.rating,
      agent.review_count,
      agent.total_installs,
      agent.version,
      agent.verified,
      agent.tags,
      agent.integrations,
      agent.capabilities,
      JSON.stringify(agent.key_benefits),
      agent.about,
      null, // icon_url
    );
    paramIdx += 19;
  }

  const sql = `
    INSERT INTO marketplace_agents
      (slug, name, description, short_description, category, developer,
       price, price_label, rating, review_count, total_installs, version,
       verified, tags, integrations, capabilities, key_benefits, about, icon_url)
    VALUES ${values.join(', ')}
    ON CONFLICT (slug) DO UPDATE SET
      name = EXCLUDED.name,
      description = EXCLUDED.description,
      short_description = EXCLUDED.short_description,
      category = EXCLUDED.category,
      developer = EXCLUDED.developer,
      price = EXCLUDED.price,
      price_label = EXCLUDED.price_label,
      rating = EXCLUDED.rating,
      review_count = EXCLUDED.review_count,
      total_installs = EXCLUDED.total_installs,
      version = EXCLUDED.version,
      verified = EXCLUDED.verified,
      tags = EXCLUDED.tags,
      integrations = EXCLUDED.integrations,
      capabilities = EXCLUDED.capabilities,
      key_benefits = EXCLUDED.key_benefits,
      about = EXCLUDED.about,
      updated_at = now()
  `;

  await client.query(sql, params);

  const { rows: [{ count }] } = await client.query('SELECT COUNT(*)::int as count FROM marketplace_agents');
  console.log(`Done! Seeded ${AGENTS.length} agents. Total in DB: ${count}`);

  await client.end();
}

main().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
